FROM centos
MAINTAINER saikumarkandlagunta@gmail.com  
RUN mkdir /opt/jenkins
WORKDIR /opt/jenkins
RUN curl -o https://downloads.apache.org/tomcat/tomcat-8/v8.5.66/bin/apache-tomcat-8.5.66.tar.gz
RUN tar xvfz apache*.tar.gz
RUN mv apache-tomcat-8.5.66/* /opt/tomcat/ .
RUN yum -y install java
RUN java -version
WORKDIR /opt/tomcat/webapps
EXPOSE 8880
CMD ["/opt/tomcat/bin/catalina.sh", "run"]
